=== MaxRS07/roomie-match/Schemas/MessageSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "_id": {
            "type": "object",
            "properties": {
                "$oid": {
                    "type": "string"
                }
            },
            "required": [
                "$oid"
            ]
        },
        "sender_id": {
            "type": "object",
            "properties": {
                "$oid": {
                    "type": "string"
                }
            },
            "required": [
                "$oid"
            ]
        },
        "receiver_id": {
            "type": "object",
            "properties": {
                "$oid": {
                    "type": "string"
                }
            },
            "required": [
                "$oid"
            ]
        },
        "content": {
            "type": "string"
        },
        "sent_at": {
            "type": "string"
        },
        "read": {
            "type": "string",
            "enum": [
                "True",
                "False"
            ]
        }
    },
    "required": [
        "_id",
        "sender_id",
        "receiver_id",
        "content",
        "sent_at",
        "read"
    ]
}

=== MaxRS07/roomie-match/Schemas/ExampleMessage.json
{
    "_id": {
        "$oid": "69c6ccce74d407f38607da6f"
    },
    "sender_id": {
        "$oid": "69c6ccce74d407f38607d9f8"
    },
    "receiver_id": {
        "$oid": "69c6ccce74d407f38607da14"
    },
    "content": "cultivate next-generation eyeballs",
    "sent_at": "11/6/2022",
    "read": "False"
}
